### ISSUE TITLE
Clarification: TypeID.fromString("") return a valid TypeID, which is weird

### ISSUE THREAD

**Issue by incompletude** [jetify-com/typeid-js#12]
Is there a reason for this behavior?

**Comment by LucilleH** [comment]
Yeah we are basically assuming that the user wants to generate a new typeID. Could be weird - but I didn't want to return `null` and make the returned typeId nullable, and throwing an exception can be a bit disruptive. 

What do you think the expected behavior should be?

**Comment by incompletude** [comment]
I'm using this method to parse TypeIDs in DTOs. If there was a TypeID.parse(string, optional type), I think the behavior is okay, but since there is not, I think it should throw an exception like other invalid strings. Or maybe I got the wrong idea about this being something like a parse.

**Comment by incompletude** [comment]
thx
