### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by izakfilmalter** [jetify-com/typeid-js#2]
Will this get published to NPM, or do we need to fork it?

**Comment by loreto** [comment]
I'll publish soon! Wanted to add one more round of tests, and then we'll publish, I can update this ticket as soon as we do.

**Comment by izakfilmalter** [comment]
Would be great to have `encodeFromUUID`.

**Comment by clintonb** [comment]
Looks like someone has taken the package name `typeid-ts`: https://www.npmjs.com/package/typeid-ts.

Source: https://github.com/ongteckwu/typeid-ts

**Comment by loreto** [comment]
Heh, yeah, looks like everyone got excited about their contributions and started publishing their own versions too.

For the official one (this one), I was hoping to do just `typeid` but npm complains that it's too similar to an existing `typedi`.

I might just publish under `@jetpack-io/typeid` unless folks have a better suggestion?

**Comment by BryceAMcDaniel** [comment]
Heads up, the npm currently listed as official of `typeid-js` readme references installation of 'typeid-ts', not currently the 'typeid-js' package like I believe is the official package.

**Comment by loreto** [comment]
Because `typeid-ts` was already taken in npm, I'm renaming everything to `typeid-js` and will publish under that name in npm. I just did the final changes to this repo (renamed it, added final tests). Now I'm gonna publish in npm and test that the package works.

**Comment by loreto** [comment]
FYI, I just published https://www.npmjs.com/package/typeid-js if anyone else wants to give it a try and tell me if it works well.

**Comment by BryceAMcDaniel** [comment]
Can confirm, worked for me. Thanks for great work!

**Comment by loreto** [comment]
Closing, since the npm package is now published.
