### ISSUE TITLE
Doesn't work in browser? 

### ISSUE THREAD

**Issue by kunchenguid** [jetify-com/typeid-js#3]
Tried this in my frontend project and surprised that is simply crashed with "Buffer is not defined". Looks like it's assuming node.js environment. Is there a plan to make this package work in the browser? Not being able to use on the frontend would severely limit the adoption.

**Comment by loreto** [comment]
You're right, we definitely want the library to be useable in the browser as well. We'll fix via https://github.com/jetpack-io/typeid-js/pull/4

**Comment by loreto** [comment]
PR is in, I'm working on creating a new release later today.

**Comment by loreto** [comment]
@atinylittleshell I published a new version on NPM with the change. Could you try the latest `0.2.1` version and see if that works for you?

**Comment by loreto** [comment]
Should now be fixed as part of release `0.2.1`

**Comment by kunchenguid** [comment]
@loreto works like a charm. Thanks!!
