### ISSUE TITLE
Branded type usage 

### ISSUE THREAD

**Issue by cxvvs** [jetify-com/typeid-js#6]
Any plans to make TypeIDs even safer at the type level using nominal typing ?

It would be great to have an API that fails typechecking for instances like these : 
```typescript

function getUser(userId: TypeID<'user'>) { ... }

const userId = typeid('user')  // Inferred as TypeID<'user'>
const postId = typeid('post') // Inferred as TypeID<'post'>

getUser(userId) // Ok
getUser(postId) // Fails at compile time
```

New parsing functions could be added to instanciate properly typed TypeIDs : 

```typescript
// Inferred as TypeId<'prefix'
const prefixId = TypeID.fromPrefixedString('prefix', 'prefix_00041061050r3gg28a1c60t3gf') 

// Inferred as TypeId<'prefix'> but fails at runtime.
const otherPrefixId = TypeID.fromPrefixedString('prefix', 'other_00041061050r3gg28a1c60t3gf') 

```

**Comment by loreto** [comment]
Yes, I think that's a great idea. We're actually having a discussion around it in this PR https://github.com/jetpack-io/opensource/pull/88

**Comment by cxvvs** [comment]
Great ! Closing this issue to avoid clutter then.

**Comment by loreto** [comment]
Just to keep everyone updated, I now have an open PR here: https://github.com/jetpack-io/opensource/pull/91 which we'll merge soon

**Comment by loreto** [comment]
Version `0.3.0` is now published on npm https://www.npmjs.com/package/typeid-js with the new type checking functionality.

**Comment by xprnio** [comment]
Thanks again for pulling my ideas into the project :D I can finally use TypeID the way I assumed it should be used from the get-go :D 

![image](https://github.com/jetpack-io/typeid-js/assets/3042904/5d3574fe-bd2f-43b0-86f3-025e819789a1)
