### ISSUE TITLE
Unboxed TypeScript implementation of TypeIDs

### ISSUE THREAD

**Issue by ozanvos** [jetify-com/typeid-js#9]
Hi, first of all thanks for this project! I liked using it for my project but had some trouble because of the in-memory representation of TypeIDs using class instances.

One issue was that I needed to serialize and de-serialize it using a custom type in [Drizzle ORM](https://orm.drizzle.team/):

```typescript
const makeCustomId = <T extends string>(dbName: string, prefix: T) =>
  customType<{
    data: TypeID<T>;
    driverData: string;
  }>({
    dataType() {
      return "string";
    },
    fromDriver(value: string): TypeID<T> {
      return TypeID.fromString(value).asType(prefix);
    },
  })(dbName);
```

This works, apart from seeing `[Object object]` in some devtools.

Another issue was returning TypeID values from a Qwik City [`routeLoader$`](https://qwik.dev/docs/route-loader/). It gives an error that it can't serialize these values as it only supports serializing JS primitives, arrays and plain objects. This meant I had to map every value I get from db first to update the IDs to string, and then back to TypeID's on the client side.

To make my workflow easier, I forked typeid-js and built an alternative that always represents TypeIDs as strings at runtime, provides some helper functions, and uses branded TypeScript types for type safety: https://github.com/ozanmakes/typeid-unboxed

I'm curious to hear what you think. Is this something you'd like to include in this package? Otherwise, do you bless such an approach and would you mind if I publish this on npm under this name or something else?

**Comment by loreto** [comment]
@LucilleH to take a look

**Comment by LucilleH** [comment]
@ozanmakes I can see why a class representation is problematic for serialization. I think we should include your implementation in the package directly 👍 

Do you mind doing the following?
1. Add your functional version of the typeid implementation
2. Keep the original class interface for backwards compatibility

**Comment by ozanvos** [comment]
Great @LucilleH . Do you have a suggestion for the import path? `import { type TypeID } from 'typeid/<something>'`?

**Comment by LucilleH** [comment]
> Great @LucilleH . Do you have a suggestion for the import path? `import { type TypeID } from 'typeid/<something>'`?

Maybe `typeid/common`? Although, we don't want to publish a sub-package.

@ozanmakes Thoughts?

**Comment by tylermercer** [comment]
I've also run into this problem. I'm trying to use them as IDs in IndexedDB. @ozanmakes thank you for publishing your solution! I will use that for now, and will switch back to this package once it supports this use case.

**Comment by JasonYao** [comment]
+1, thanks @ozanmakes for the solution here, your solution definitely saves a bunch of headache when using `typeid-js` in practice.

For reference to anybody else, but thanks to the unboxing technique in @ozanmakes's fork, it allows for using `TypeIds` as keys in `Map`s and `Set`s natively- so instead of:

```ts
// Previous solution using 0.5.0 of typeid-js
const someMap = new Map<string, string>() // Note that we lose type safety here

const exampleTypeId = TypeID.fromString('example_01htbw6k1afr8rvybjc2jm0eqg').asType('example')

// Note that we needed to manually call .toString() here
const result = someMap.get(exampleTypeId.toString())
```

now with the `typeid-unboxed` solution, we get the capability to just do this:

```ts
type ExampleId = TypeID<'example'>
const someMap = new Map<ExampleId, string>() // Note that we maintain type safety here

const exampleTypeId = fromString('example_01htbw6k1afr8rvybjc2jm0eqg', 'example')

// Note that there's no need to call .toString()
const result = someMap.get(exampleTypeId)
```

In all honesty, the solution might be worth considering as just adding in as a breaking change and just bumping the version number to 1.0, since this package is still in the 0.x range, but that's more of a maintainer decision

**Comment by LucilleH** [comment]
@ozanmakes @JasonYao @tylermercer v0.6.0 is published with `typeidUnboxed()`. Let me know if this works for you all.

Thanks again @ozanmakes for your suggestion and implementation!
